apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhg-backend-chart.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "fhg-backend-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8080
